#!/bin/bash
function instl (){

if [[ -z `dpkg -l | grep "Robot OS"` ]]
then echo "You need install ROS"
echo ""
./rbnmcs_instl
fi

#mkdir -p ws/src && cd ws/src
#git clone https://github.com/airalab/robonomics_comm
#catkin_init_workspace && cd .. && catkin_make 
wget http://bootstrap.aira.life/robonomics.sh
chmod +x ./robonomics.sh
./robonomics.sh init        # for the first time only
./robonomics.sh mainnet     # or sidechain for Sidechain network
rm robonomics.sh
}


function instl_with_ros (){

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt install ros-melodic-desktop-full

echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
source ~/.bashrc

sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential

sudo apt install python-rosdep

sudo rosdep init
rosdep update

instl
}


echo "This script installs Robonomics by Airtable"

if [[ -n `dpkg -l | grep robonomics` ]]
then echo "You have already installed Robonomics"
return 0
fi


echo "1 is installation Robonomics and  ROS"
echo "2 is installation Robonomics only"
read -p "What type do you need? " answer

case $answer in
1) instl_with_ros;;
2) instl;;
esac
