#!/bin/bash
#clear
IFS=$'\n'

function func () {

for line in `ls -l`
do

rights=`echo $line | awk '{print $1}'`
size=`echo $line | awk '{print $5}'`
date=`echo $line | awk '{print $7 $6 $8}'`

name=`echo $line | awk '{print $9}'`
type=`echo $name | awk -F '.' '{print $2}'`

duration=`ffprobe "$name" 2>&1 | awk -F '[:,]' '/Duration/ {printf("%d:%d:%g", $2,$3,$4)}'`

name=`echo $name | awk -F '.' '{print $1}'`


if [[ "$size" -ne "" ]]
then echo $name,$type,$size,$rights,$date,$duration
	duration="" 
fi

if [ `echo $rights` = "drwxr-xr-x" ]
then 	
	cd $name/
	func
	cd -
fi

done
}

#______________________________________________________
if [ -z `dpkg -l | grep ffmpeg` ]
then sudo apt install ffmpeg
fi

output=file_result.csv
rm $output

echo name,type,size,rights,date,duration >> $output

func | sed '/home/d' | sed '/*,*/d'  >> $output

echo "done"




